server:
  port: 8888

spring:
  application:
    name: koude-config
  cloud:
    config:
      server:
        git:
          uri: https://git.com
          username: user
          password: pass
          clone-on-start: true
          default-label: dev
logging:
  level:
    org.springframework.cloud.config.server: DEBUG