version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
variables:
  repository: registry.cn-beijing.aliyuncs.com/lun3322/koude-config
  username: lun3322@aliyun.com
  password: 123123qweQ
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '17'
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        caches:
          - ~/.m2
        strategy: {}
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: ${config_repository}
        username: ${username}
        password: ${password}
        tag: ${image_tag}:${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: true
        parameter: {}
        notify: []
        strategy:
          retry: '0'
